CXX = x86_64-w64-mingw32-g++ #g++
CXXFLAGS = -std=c++11 -Wall -g

OBJECTS = main.o file_loader.o decompress.o compress.o

main: $(OBJECTS)
	$(CXX) $(CXXFLAGS) -static-libstdc++ -static-libgcc -o $@ $^

clean:
	rm *.o main

$(OBJECTS): functions.h structs.h

